services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sales_db
      MYSQL_USER: thangquang
      MYSQL_PASSWORD: thangquang
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - thangquang

  postgres:
    image: postgres:14
    container_name: postgres_container
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=thangquang
      - POSTGRES_PASSWORD=thangquang
      - POSTGRES_DB=sales_db
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - thangquang

volumes:
  mysql_data:
  postgres_data:

networks:
  thangquang: