services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql_container
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sales_db
      MYSQL_USER: thangquang
      MYSQL_PASSWORD: thangquang
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - thangquang

  postgres:
    image: postgres:14.5
    container_name: postgres_container
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=thangquang
      - POSTGRES_PASSWORD=thangquang
      - POSTGRES_DB=sales_db
      - PGPASSWORD=thangquang # for backup data warehouse
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups 
    restart: always
    networks:
      - thangquang

  postgres_airflow:
    image: postgres:14.5
    container_name: postgres_airflow_container
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow_db
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    networks:
      - thangquang

  webserver:
    image: apache/airflow:2.6.0-python3.10
    container_name: webserver_container
    entrypoint: ['/opt/airflow/script/entrypoint.sh']
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_airflow_container/airflow_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres_airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./script/webserver_entrypoint.sh:/opt/airflow/script/entrypoint.sh
      - ./requirements.txt:/opt/airflow/requirements.txt
      - shared_airflow_libs:/home/airflow/.local/lib/python3.10/site-packages
    healthcheck:
      test: ['CMD-SHELL', "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 2m
      retries: 10
    restart: always
    networks:
      - thangquang

  scheduler:
    image: apache/airflow:2.6.0-python3.10
    container_name: scheduler_container
    depends_on:
      webserver:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./script/scheduler_entrypoint.sh:/opt/airflow/script/entrypoint.sh
      - ./requirements.txt:/opt/airflow/requirements.txt
      - shared_airflow_libs:/home/airflow/.local/lib/python3.10/site-packages
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_airflow_container/airflow_db
    command: ["bash", "/opt/airflow/script/entrypoint.sh", "airflow", "scheduler"]
    restart: always
    networks:
      - thangquang

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False' 
      PGADMIN_CONFIG_CONNECTIONS: 'True'
      PGADMIN_SERVER: 'postgres_container'
      PGADMIN_SERVER_USER: 'thangquang'
      PGADMIN_SERVER_PASSWORD: 'thangquang'
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - thangquang

volumes:
  mysql_data:
  postgres_data:
  postgres_airflow_data:
  shared_airflow_libs:

networks:
  thangquang:
