-- RDBMS: PostgreSQL
DROP MATERIALIZED VIEW IF EXISTS view_store_city_employee_cus;
DROP MATERIALIZED VIEW IF EXISTS view_quantity_cate_store_city;
DROP MATERIALIZED VIEW IF EXISTS view_online_offline_summary;

DROP TABLE IF EXISTS Fact_Sales_Order;
DROP TABLE IF EXISTS Fact_Production;
DROP TABLE IF EXISTS Dim_Product;
DROP TABLE IF EXISTS Dim_Brand;
DROP TABLE IF EXISTS Dim_Category;
DROP TABLE IF EXISTS Dim_Date;
DROP TABLE IF EXISTS Dim_Month;
DROP TABLE IF EXISTS Dim_Quarter;
DROP TABLE IF EXISTS Dim_Year;
DROP TABLE IF EXISTS Dim_Source_Online;
DROP TABLE IF EXISTS Dim_Customer;
DROP TABLE IF EXISTS Dim_Employee;
DROP TABLE IF EXISTS Dim_Store;
DROP TABLE IF EXISTS Dim_City;